[package]
name = "cartesi-machine"
version = { workspace = true }
edition = { workspace = true }

authors = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
license-file = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }


[features]
remote_machine = ["cartesi-machine-sys/remote_machine"]

[dependencies]
cartesi-machine-sys = { path = "../cartesi-machine-sys" }

hex = "0.4.3"
num-traits = "0.2"
num-derive = "0.4"
