[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true

allow_paths = ['../../machine/step/']
remappings = [
    'prt-contracts/=./src',
    'step/=../../machine/step/',
]
solc-version = "0.8.27"

[fmt]
line_length = 80
tab_width = 4
