[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
auto_detect_remappings = false
via_ir = true
optimizer = true

allow_paths = ['../../machine/step/']
remappings = [
    "@openzeppelin-contracts-5.5.0/=dependencies/@openzeppelin-contracts-5.5.0/",
    "forge-std-1.9.6/=dependencies/forge-std-1.9.6/",
    "prt-contracts/=./src",
    "step/=../../machine/step/",
]

solc_version = "0.8.30"
evm_version = "prague"

[soldeer]
remappings_location = "config"

[lint]
exclude_lints = ["incorrect-shift"]

[fmt]
line_length = 80
tab_width = 4
sort_imports = true

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.5.0"
