[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
via_ir = true
optimizer = true

allow_paths = ['../../machine/step/']
remappings = [
    'prt-contracts/=./src',
    'step/=../../machine/step/',
]

solc_version = "0.8.30"
evm_version = "prague"

[lint]
exclude_lints = ["incorrect-shift"]

[fmt]
line_length = 80
tab_width = 4
sort_imports = true

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.5.0"
